name: publish

on: workflow_dispatch

env: ${{ secrets }}

jobs:
  publish:
    uses: datavisyn/github-workflows/.github/workflows/publish-node.yml@main
    secrets:
      DV_DEVOPS: ${{ secrets.DV_DEVOPS }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      DATAVISYN_BOT_REPO_TOKEN: ${{ github.token }}
